### PR TITLE
Update ChangeLog

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by iahmad-khan** [comment]
ping

**Comment by smuzaffar** [comment]
Command ping acknowledged.

**Comment by smuzaffar** [comment]
Command ping acknowledged.

**Comment by iahmad-khan** [comment]
close

**Comment by smuzaffar** [comment]
Command close acknowledged.

**Comment by iahmad-khan** [comment]
open

**Comment by smuzaffar** [comment]
Command open acknowledged.

**Comment by iahmad-khan** [comment]
merge

**Comment by smuzaffar** [comment]
Command merge acknowledged.

**Pull request merged**
